import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import { ThemeProvider } from '@/utils/Themeprovider'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className='font-custom'>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </body>
      </ThemeProvider>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
